global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'llm-api'
    static_configs:
      - targets: ['host.docker.internal:8001']
    scrape_interval: 5s
    metrics_path: /metrics